import { test, expect, type Page } from '@playwright/test';
async function setup(page:Page,width=1440) {
 await page.setViewportSize({width,height:900});
 await page.addInitScript(()=>{localStorage.setItem('cadentrail:profile',JSON.stringify({name:'',welcomed:true}));localStorage.setItem('studio:experience','create');});
 await page.request.post('/api/auth',{data:{password:'cadentrail-browser-test'}});
 return await(await page.request.post('/api/_test/takes')).json();
}
test.afterEach(async({page})=>{await page.request.post('/api/_test/reset-signin');});
for(const width of [1440,390]) test(`assistant contexts, draft history and language at ${width}px`,async({page})=>{
 const p=await setup(page,width);
 p.creative.lyricDrafts=[['enhance','A warm Japanese city-pop duet'],['generate','Original saved lyrics'],['arrange','[intro]\n[verse]\n[chorus]\n[outro]']].map(([operation,text],i)=>({id:String(i).repeat(32),operation,text,model:'Qwen/Qwen3-1.7B',createdAt:1,seed:1,jobId:null}));
 expect((await page.request.put('/api/projects/'+p.id,{data:p})).ok()).toBeTruthy();
 let checks=0;
 await page.route('**/api/providers',async route=>{checks++;if(checks===1){await route.fulfill({status:503,json:{detail:'Temporary test outage'}});return;}const data=await(await route.fetch()).json();data.text.available=true;await route.fulfill({json:data});});
 const requests:any[]=[];
 await page.route('**/api/jobs',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const data=route.request().postDataJSON();requests.push(data);await route.fulfill({json:{id:'test-job',projectId:p.id,kind:'lyrics',state:'Queued',createdAt:Date.now()/1000,updatedAt:Date.now()/1000,message:'Test queue',request:data}});});
 await page.goto('/#'+p.id);
 const steps=page.locator('.create-steps');
 await steps.getByRole('button',{name:/Sound/}).click();
 await page.getByRole('button',{name:'Enhance description',exact:true}).click();
 const desk=page.getByRole('complementary',{name:'Song assistant'});
 await expect(desk.getByRole('button',{name:'Draft description',exact:true})).toBeDisabled();
 await desk.getByRole('button',{name:'Retry connection',exact:true}).click();
 await expect(desk.getByRole('button',{name:'Draft description',exact:true})).toBeEnabled();
 await expect(desk.getByRole('button',{name:'Description',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(desk.getByLabel('Music description · editable suggestion')).toHaveValue('A warm Japanese city-pop duet');
 await desk.getByLabel('Music description · editable suggestion').fill('Keep this unsaved description draft');
 await desk.getByRole('button',{name:'Lyrics',exact:true}).click();
 await expect(desk.getByRole('button',{name:'Lyrics',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(desk.getByLabel('Lyrics · editable suggestion')).toHaveValue('Original saved lyrics');
 await desk.getByLabel('Lyric language',{exact:true}).selectOption('ja');
 await desk.getByRole('button',{name:'Write a draft',exact:true}).click();
 await expect.poll(()=>requests.length).toBe(1);expect(requests[0].options.language).toBe('ja');expect(requests[0].options.operation).toBe('generate');
 await desk.getByRole('button',{name:'Description',exact:true}).click();
 await expect(desk.getByLabel('Music description · editable suggestion')).toHaveValue('Keep this unsaved description draft');
 // Changing the creation step also changes the assistant focus.
 await steps.getByRole('button',{name:/Words/}).click();
 await expect(desk.getByRole('button',{name:'Lyrics',exact:true})).toHaveAttribute('aria-pressed','true');
 await desk.getByRole('button',{name:'Back to my song',exact:true}).click();
 await page.getByRole('button',{name:'Instrumental',exact:true}).click();
 await expect(page.getByRole('button',{name:'Generate lyrics',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Suggest arrangement',exact:true}).click();
 await expect(desk.getByRole('button',{name:'Arrangement',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(desk.getByRole('button',{name:'Lyrics',exact:true})).toHaveCount(0);
 await desk.getByRole('button',{name:'Use arrangement',exact:true}).click();
 await expect.poll(async()=> (await(await page.request.get('/api/projects/'+p.id)).json()).generation.instrumentalSections).toBe('[intro]\n[verse]\n[chorus]\n[outro]');
 await desk.getByRole('button',{name:'Suggest arrangement',exact:true}).click();
 await expect.poll(()=>requests.length).toBe(2);expect(requests[1].options.operation).toBe('arrange');expect(requests[1].options.lyrics).toBe('');expect(requests[1].options.instrumental).toBe(true);
 const saved=await(await page.request.get('/api/projects/'+p.id)).json();expect(saved.generation.lyrics).toBe(p.generation.lyrics);expect(saved.creative.assistanceLanguage).toBe('ja');
 await page.screenshot({path:`.runtime/046-assistant-${width}.png`,animations:'disabled'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
});
for(const width of [1440,390]) test(`new project and search preserve edits at ${width}px`,async({page})=>{
 const p=await setup(page,width);await page.goto('/#'+p.id);
 const toolbar=page.getByRole('toolbar',{name:'Project actions'});
 await toolbar.getByRole('button',{name:'New project',exact:true}).click();
 await page.getByLabel('New project name',{exact:true}).fill('A fresh idea '+width);
 await page.getByRole('button',{name:'Create song',exact:true}).click();
 await expect(page.getByLabel('Project name',{exact:true})).toHaveValue('A fresh idea '+width);
 const freshId=(await page.evaluate(()=>location.hash)).slice(1);
 await page.getByLabel('Music description',{exact:true}).fill('Unsaved Japanese jazz idea');
 await toolbar.getByRole('button',{name:'Switch project',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Switch project',exact:true});
 await dialog.getByLabel('Search projects',{exact:true}).fill('no match anywhere');
 await expect(dialog.getByText('No projects match.',{exact:false})).toBeVisible();
 await dialog.getByLabel('Search projects',{exact:true}).fill(p.name);
 await page.screenshot({path:`.runtime/046-projects-${width}.png`,animations:'disabled'});
 await dialog.getByRole('button',{name:'Open project '+p.name,exact:true}).first().click();
 await expect(page.getByLabel('Project name',{exact:true})).toHaveValue(p.name);
 expect((await(await page.request.get('/api/projects/'+freshId)).json()).generation.style).toBe('Unsaved Japanese jazz idea');
 // A failed save must keep the current project and switcher open.
 await page.route('**/api/projects/'+p.id,route=>route.request().method()==='PUT'?route.fulfill({status:503,json:{detail:'Save test outage'}}):route.continue());
 await page.getByLabel('Project name',{exact:true}).fill('Do not lose this title');
 await toolbar.getByRole('button',{name:'Switch project',exact:true}).click();
 await dialog.getByLabel('Search projects',{exact:true}).fill('A fresh idea '+width);
 await dialog.getByRole('button',{name:'Open project A fresh idea '+width,exact:true}).click();
 await expect(dialog.getByText('The project could not be opened.',{exact:false})).toBeVisible();
 expect((await page.evaluate(()=>location.hash)).slice(1)).toBe(p.id);
 await page.unroute('**/api/projects/'+p.id);
 await dialog.getByRole('button',{name:'Close project switcher',exact:true}).click();
 await expect(page.getByLabel('Project name',{exact:true})).toHaveValue('Do not lose this title');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
});
test('automatic video follows the selected take and remembers explicit choices',async({page})=>{
 const p=await setup(page);const instrumental=p.candidates[0].assetId,vocal=p.candidates[1].assetId;
 p.candidates[0].metadata.generation.role='instrumental';p.visuals.video.audioAssetId=instrumental;
 expect((await page.request.put('/api/projects/'+p.id,{data:p})).ok()).toBeTruthy();await page.goto('/#'+p.id);
 await page.getByRole('navigation',{name:'Workspaces'}).getByRole('button',{name:'Visuals',exact:true}).click();
 await page.getByRole('navigation',{name:'Visual editors'}).getByRole('button',{name:'Music video',exact:true}).click();
 const checkbox=page.getByRole('checkbox',{name:'Include lyrics when timing is reliable'}),song=page.locator('.quick-video-controls').getByRole('combobox',{name:'Song',exact:true});
 await expect(checkbox).not.toBeChecked();await checkbox.check();await song.selectOption(vocal);await expect(checkbox).toBeChecked();await checkbox.uncheck();await song.selectOption(instrumental);await expect(checkbox).toBeChecked();await song.selectOption(vocal);await expect(checkbox).not.toBeChecked();
});
