import {test,expect,devices,type Page} from "@playwright/test";
const password="cadentrail-browser-test";
async function enter(page:Page){
 await page.addInitScript(()=>{localStorage.setItem("cadentrail:profile",JSON.stringify({name:"",welcomed:true}));localStorage.setItem("cadentrail:mode","radio");});
 await page.request.post("/api/auth",{data:{password}});
 const current=await (await page.request.get("/api/radio/current")).json();
 if(current)await page.request.delete("/api/radio/"+current.id);
 const p=await (await page.request.post("/api/projects",{data:{name:"Radio interaction check"}})).json();
 await page.goto("/#"+p.id);
 await expect(page.getByRole("heading",{name:"What sounds good today?"})).toBeVisible();
}
for(const width of [1440,390])test(`live auto-join and station direction at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:width===390?844:900});await enter(page);
 await page.getByRole("combobox",{name:"Lyric language",exact:true}).selectOption("ja");
 const before=await (await page.request.get("/api/projects")).json();
 const station=await (await page.request.post("/api/_test/radio")).json();
 await expect(page.getByRole("heading",{name:"Radio browser check 1"})).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused&&a.currentTime>=12))).toBeTruthy();
 await expect(page.getByRole("button",{name:/Pause|Skip|Next track/i})).toHaveCount(0);
 await expect(page.getByRole("slider")).toHaveCount(1);
 await page.getByRole("button",{name:"Adjust station",exact:true}).click();
 await page.getByLabel("Shape the next songs").fill("Japanese J-pop with an acoustic evening mood");
 await page.getByRole("combobox",{name:"Lyric language",exact:true}).selectOption("ja");
 await page.screenshot({path:`.runtime/radio-direction-${width}.png`});
 await page.locator("form.radio-retune").screenshot({path:`.runtime/radio-direction-form-${width}.png`});
 await page.getByRole("button",{name:"Apply direction",exact:true}).click();
 await expect(page.getByText("Preparing your new direction. Current music keeps playing.")).toBeVisible();
 const changed=await (await page.request.get("/api/radio/current")).json();
 expect(changed.id).toBe(station.id);expect(changed.revision).toBe(2);
 expect(changed.tracks.map((t:any)=>t.id)).toEqual(station.tracks.map((t:any)=>t.id));
 expect(changed.tracks[0].startedAt).toBe(station.tracks[0].startedAt);
 await page.getByRole("button",{name:"Adjust station",exact:true}).click();
 await page.getByRole("button",{name:"Classical",exact:true}).click();
 await page.getByRole("button",{name:"Apply direction",exact:true}).click();
 await expect(page.getByText("Instrumental requested",{exact:true})).toBeVisible();
 const classical=await (await page.request.get("/api/radio/current")).json();
 expect(classical.id).toBe(station.id);expect(classical.revision).toBe(3);
 expect(classical.effectiveVocals).toBe("instrumental");
 expect(classical.tracks[0].startedAt).toBe(station.tracks[0].startedAt);
 expect(await (await page.request.get("/api/projects")).json()).toEqual(before);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 await page.reload();
 await expect(page.getByRole("heading",{name:"Radio browser check 1"})).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused&&a.currentTime>12))).toBeTruthy();
 await page.getByRole("button",{name:"Mute radio",exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused))).toBeTruthy();
 await page.getByRole("button",{name:"Stop Radio",exact:true}).click();
 await expect(page.getByRole("heading",{name:"What sounds good today?"})).toBeVisible();
 expect(await (await page.request.get("/api/radio/current")).json()).toBeNull();
});
test("autoplay refusal offers Join live instead of a pause toggle",async({page})=>{
 await page.addInitScript(()=>{
   const play=HTMLMediaElement.prototype.play;let blocked=true;
   document.addEventListener("pointerdown",()=>{blocked=false;},{once:true});
   HTMLMediaElement.prototype.play=function(){return blocked?Promise.reject(new DOMException("Audio needs a gesture","NotAllowedError")):play.call(this);};
 });
 await enter(page);await page.request.post("/api/_test/radio");
 await expect(page.getByRole("button",{name:"Join live",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Join live",exact:true}).click();
 await expect(page.getByRole("button",{name:"Join live",exact:true})).toBeHidden();
 await expect(page.getByRole("button",{name:/Pause/})).toHaveCount(0);
 await page.getByRole("button",{name:"Stop Radio",exact:true}).click();
});

test.afterEach(async ({page})=>{await page.request.post("/api/_test/reset-signin");});

for(const width of [1440,390])test(`saved stations keep full settings at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844});await enter(page);
 await page.getByLabel("The music you want to hear").fill("Classical piano and strings for focus");
 await page.getByRole("combobox",{name:"Lyric language",exact:true}).selectOption("ja");
 await page.locator(".radio-presets summary").click();
 await page.getByRole("button",{name:"Save current settings",exact:true}).click();
 const name="Focus "+width;await page.getByLabel("Station name",{exact:true}).fill(name);
 await page.getByRole("button",{name:"Save station",exact:true}).click();
 await expect(page.getByRole("button",{name:"Use station "+name,exact:true})).toBeVisible();
 await page.reload();await page.locator(".radio-presets summary").click();
 await page.getByRole("button",{name:"Use station "+name,exact:true}).click();
 await expect(page.getByLabel("The music you want to hear")).toHaveValue("Classical piano and strings for focus");
 await expect(page.getByRole("combobox",{name:"Lyric language",exact:true})).toHaveValue("ja");
 await page.getByRole("button",{name:"Edit saved station "+name,exact:true}).click();
 await page.getByLabel("Station name",{exact:true}).fill(name+" renamed");await page.getByRole("button",{name:"Save station",exact:true}).click();
 await expect(page.getByRole("button",{name:"Use station "+name+" renamed",exact:true})).toBeVisible();
 await page.locator(".radio-presets").screenshot({path:`.runtime/043-presets-${width}.png`});
 const before=await (await page.request.get("/api/projects")).json();const station=await (await page.request.post("/api/_test/radio")).json();
 await expect(page.getByRole("heading",{name:"Radio browser check 1"})).toBeVisible();
 await page.locator(".radio-presets summary").click();
 await page.getByRole("button",{name:"Use station "+name+" renamed",exact:true}).click();
 await expect(page.getByLabel("Shape the next songs")).toHaveValue("Classical piano and strings for focus");
 await page.getByRole("button",{name:"Apply direction",exact:true}).click();
 await expect(page.getByText("Instrumental requested",{exact:true})).toBeVisible();
 const current=await (await page.request.get("/api/radio/current")).json();expect(current.id).toBe(station.id);expect(current.tracks[0].startedAt).toBe(station.tracks[0].startedAt);
 expect(await (await page.request.get("/api/projects")).json()).toEqual(before);
 await page.getByRole("button",{name:"Remove saved station "+name+" renamed",exact:true}).click();await page.getByRole("button",{name:"Remove station",exact:true}).click();
 await expect(page.getByRole("button",{name:"Use station "+name+" renamed",exact:true})).toHaveCount(0);
 expect((await (await page.request.get("/api/radio/current")).json()).id).toBe(station.id);
 await page.getByRole("button",{name:"Stop Radio",exact:true}).click();
});
test.describe("Android-sized touch playback",()=>{
 test.use({viewport:devices["Pixel 7"].viewport,userAgent:devices["Pixel 7"].userAgent,deviceScaleFactor:devices["Pixel 7"].deviceScaleFactor,isMobile:true,hasTouch:true});
 test("rejoins after connectivity loss without changing the server session",async({page,context})=>{
  await enter(page);const first=await (await page.request.post("/api/_test/radio")).json();
  await expect(page.getByRole("heading",{name:"Radio browser check 1"})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused))).toBeTruthy();
  await context.setOffline(true);await expect(page.getByText("Connection lost. Buffered music can continue.")).toBeVisible();
  const next=await (await page.request.post("/api/_test/radio/clock")).json();expect(next.id).toBe(first.id);
  await context.setOffline(false);
  await expect(page.getByRole("heading",{name:"Radio browser check 3"})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused&&a.currentTime>=7&&a.currentTime<20))).toBeTruthy();
  await expect(page.getByRole("button",{name:"Reconnect",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"Mute radio",exact:true}).tap();
  await expect.poll(()=>page.evaluate(()=>navigator.mediaSession.playbackState)).toBe("paused");
  await expect.poll(()=>page.evaluate(()=>Array.from(document.querySelectorAll<HTMLAudioElement>('[data-player="radio"]')).some(a=>!a.paused))).toBeTruthy();
  await page.getByRole("button",{name:"Unmute radio",exact:true}).tap();
  await expect.poll(()=>page.evaluate(()=>navigator.mediaSession.playbackState)).toBe("playing");
  await page.setViewportSize({width:844,height:390});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await expect(page.getByRole("button",{name:/Pause|Skip|Next track/i})).toHaveCount(0);
  await page.getByRole("button",{name:"Stop Radio",exact:true}).tap();
 });
});
