"""Keep browser visual types/defaults in sync with the validated project contract."""
import json
from pathlib import Path
from backend.visual_schema import Visuals,Creative

def ts(schema):
    if '$ref' in schema:return schema['$ref'].split('/')[-1]
    if 'enum' in schema:return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'anyOf' in schema:return ' | '.join(ts(s) for s in schema['anyOf'])
    kind=schema.get('type')
    if kind=='array':return '('+ts(schema['items'])+')[]'
    if kind=='object':
        if 'properties' in schema:return '{\n'+''.join(f'  {key}{"?" if value.get("clientOptional") else ""}: {ts(value)};\n' for key,value in schema['properties'].items())+'}'
        return 'Record<string, unknown>'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')

models={}
for model in (Visuals,Creative):
    schema=model.model_json_schema();models.update(schema.get('$defs',{}));models[model.__name__]=schema
text='// Generated by scripts/generate_visual_types.py.\n'
for name,schema in models.items():text+=f'export type {name} = {ts(schema)};\n'
text+='export const newVisuals = (): Visuals => ('+json.dumps(Visuals().model_dump(),indent=2)+');\n'
text+='export const newCreative = (): Creative => ('+json.dumps(Creative().model_dump(),indent=2)+');\n'
Path('src/visual-model.ts').write_text(text,encoding='utf-8')
