// Generated by scripts/generate_visual_types.py.
export type ArtworkDesign = {
  prompt: string;
  negativePrompt: string;
  aspect: "1:1" | "16:9" | "9:16" | "4:5";
  count: 1 | 2 | 4;
  seed: number;
  style: string;
  mood: string;
  characters: "none" | "suggested";
  environment: string;
  colors: string;
  composition: string;
  steps: number;
};
export type CoverDesign = {
  backgroundId: string | null;
  title: string;
  artist: string;
  subtitle: string;
  font: "sans" | "serif" | "mono";
  align: "left" | "center" | "right";
  size: number;
  tracking: number;
  color: string;
  background: string;
  overlay: number;
  scale: number;
  x: number;
  y: number;
  textY: number;
  stroke: number;
  shadow: boolean;
};
export type LyricLine = {
  id: string;
  text: string;
  start: number | null;
  end: number | null;
  confidence: number | null;
  source: "manual" | "transcription-match" | "forced-alignment";
  words: TimedWord[];
  section: string;
  voice?: "a" | "b" | "c" | "d" | "together" | null;
  voiceSource?: "manual" | "lyrics" | "detected" | null;
  voiceConfidence?: number | null;
};
export type LyricTiming = {
  assetId: string | null;
  sourceLyrics: string;
  language: string;
  model: string | null;
  jobId: string | null;
  coverage: number | null;
  needsReview: boolean;
  lines: LyricLine[];
  voices?: LyricVoice[];
  speakerModel?: string | null;
  warnings?: string[];
};
export type LyricVoice = {
  id: "a" | "b" | "c" | "d";
  name: string;
};
export type TimedWord = {
  id: string;
  text: string;
  start: number | null;
  end: number | null;
  confidence: number | null;
  source: "manual" | "transcription-match" | "forced-alignment";
};
export type VideoDesign = {
  preview: boolean;
  audioAssetId: string | null;
  backgroundId: string | null;
  kind: "karaoke" | "lyric" | "visualizer";
  template: "clean" | "classic" | "cinematic" | "minimal" | "visualizer";
  preset: "1080p" | "1080p60" | "1440p" | "4k" | "vertical" | "square";
  duration: number | null;
  start: number;
  font: "sans" | "serif" | "mono";
  fontSize: number;
  lyricY: number;
  color: string;
  highlight: string;
  background: string;
  visualizer:
    | "none"
    | "waveform"
    | "mirrored"
    | "bars"
    | "circle"
    | "scope"
    | "particles";
  sensitivity: number;
  smoothing: number;
  thickness: number;
  opacity: number;
  visualizerY: number;
  visualizerX: number;
  visualizerSize: number;
  motion: "still" | "zoom" | "pan";
  beatPulse: boolean;
  intro: boolean;
  encoder: "h264" | "hevc" | "av1" | "webm" | "archive";
  crf: number;
  scenes: VideoScene[];
};
export type VideoScene = {
  id: string;
  type:
    | "image"
    | "video"
    | "color"
    | "text"
    | "lyrics"
    | "waveform"
    | "spectrum"
    | "title";
  start: number;
  end: number;
  assetId: string | null;
  text: string;
  color: string;
  opacity: number;
  x: number;
  y: number;
  size: number;
  motion: "still" | "zoom" | "pan";
  fade: number;
};
export type VisualAsset = {
  id: string;
  name: string;
  kind: "image" | "cover" | "video";
  path: string;
  width: number;
  height: number;
  duration: number | null;
  createdAt: number;
  prompt: string;
  negativePrompt: string;
  model: string;
  seed: number | null;
  jobId: string | null;
  sourceAssetId: string | null;
  candidateId: string | null;
  parentId: string | null;
  settings: Record<string, unknown>;
};
export type Visuals = {
  artwork: ArtworkDesign;
  assets: VisualAsset[];
  coverId: string | null;
  cover: CoverDesign;
  timing: LyricTiming;
  video: VideoDesign;
  timingHistory: LyricTiming[];
};
export type LyricDraft = {
  language?: string | null;
  languageConfidence?: number | null;
  id: string;
  createdAt: number;
  jobId: string | null;
  text: string;
  model: string;
  operation: string;
  seed: number;
};
export type Creative = {
  assistanceLanguage?: string;
  assistanceModel: string | null;
  candidates: 1 | 2 | 4 | 8;
  selectedCandidateId: string | null;
  parentId: string | null;
  quality: "fast" | "balanced" | "high" | "maximum" | "custom";
  lyricDrafts: LyricDraft[];
};
export const newVisuals = (): Visuals => ({
  artwork: {
    prompt: "",
    negativePrompt: "text, letters, watermark, signature, blurry",
    aspect: "1:1",
    count: 1,
    seed: 831001,
    style: "Editorial illustration",
    mood: "",
    characters: "none",
    environment: "",
    colors: "",
    composition: "Strong focal point, space for title",
    steps: 30,
  },
  assets: [],
  coverId: null,
  cover: {
    backgroundId: null,
    title: "",
    artist: "",
    subtitle: "",
    font: "sans",
    align: "left",
    size: 80,
    tracking: 0,
    color: "#ffffff",
    background: "#202329",
    overlay: 0.25,
    scale: 1,
    x: 0.5,
    y: 0.5,
    textY: 0.72,
    stroke: 0,
    shadow: true,
  },
  timing: {
    assetId: null,
    sourceLyrics: "",
    language: "auto",
    model: null,
    jobId: null,
    coverage: null,
    needsReview: true,
    lines: [],
    voices: [],
    speakerModel: null,
    warnings: [],
  },
  video: {
    preview: false,
    audioAssetId: null,
    backgroundId: null,
    kind: "karaoke",
    template: "clean",
    preset: "1080p",
    duration: null,
    start: 0,
    font: "sans",
    fontSize: 58,
    lyricY: 0.76,
    color: "#ffffff",
    highlight: "#f1b766",
    background: "#14171d",
    visualizer: "waveform",
    sensitivity: 1,
    smoothing: 0.7,
    thickness: 3,
    opacity: 0.75,
    visualizerY: 0.5,
    visualizerX: 0.5,
    visualizerSize: 0.8,
    motion: "zoom",
    beatPulse: false,
    intro: true,
    encoder: "h264",
    crf: 18,
    scenes: [],
  },
  timingHistory: [],
});
export const newCreative = (): Creative => ({
  assistanceLanguage: "auto",
  assistanceModel: null,
  candidates: 2,
  selectedCandidateId: null,
  parentId: null,
  quality: "balanced",
  lyricDrafts: [],
});
